export  const typeData = {
    normal: { icon: 'circle', color: '#A8A878' },
    fire: { icon: 'fire', color: '#F08030' },
    water: { icon: 'tint', color: '#6890F0' },
    electric: { icon: 'bolt', color: '#F8D030' },
    grass: { icon: 'leaf', color: '#78C850' },
    ice: { icon: 'snowflake', color: '#98D8D8' },
    fighting: { icon: 'fist-raised', color: '#C03028' },
    poison: { icon: 'skull-crossbones', color: '#A040A0' },
    ground: { icon: 'mountain', color: '#E0C068' },
    flying: { icon: 'dove', color: '#A890F0' },
    psychic: { icon: 'brain', color: '#F85888' },
    bug: { icon: 'bug', color: '#A8B820' },
    rock: { icon: 'gem', color: '#B8A038' },
    ghost: { icon: 'ghost', color: '#705898' },
    dark: { icon: 'moon', color: '#705848' },
    steel: { icon: 'shield-alt', color: '#B8B8D0' },
    dragon: { icon: 'dragon', color: '#EE99AC' },
    fairy: { icon: 'fa-solid fa-wand-magic', color: '#D685AD' },
  };